spring:
  application:
    name: notification_dispatcher
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672
    username: guest
    password: guest
rabbitmq:
  exchange:
    name: notifications.direct
  queues:
    email: email.queue
    push: push.queue
    failed: failed.queue
  routing-keys:
    email: email
    push: push
    failed: failed
server:
  port: 5002
